services:
    madeyourday.rocksolid_slider.slideproviders:
        class: MadeYourDay\RockSolidSlider\SlideProvider\SlideProviderRegistry
        arguments: []

    madeyourday.rocksolid_slider.slideprovider.frontend_adapter:
        class: Contao\CoreBundle\Framework\Adapter
        arguments: ['Contao\Frontend']

    madeyourday.rocksolid_slider.slideprovider.module_model_adapter:
        class: Contao\CoreBundle\Framework\Adapter
        arguments: ['Contao\ModuleModel']

    madeyourday.rocksolid_slider.slideprovider.slider_model_adapter:
        class: Contao\CoreBundle\Framework\Adapter
        arguments: ['MadeYourDay\RockSolidSlider\Model\SliderModel']

    madeyourday.rocksolid_slider.slideprovider.slide_model_adapter:
        class: Contao\CoreBundle\Framework\Adapter
        arguments: ['MadeYourDay\RockSolidSlider\Model\SlideModel']

    madeyourday.rocksolid_slider.slideprovider.default:
        class: MadeYourDay\RockSolidSlider\SlideProvider\DefaultSlidesProvider
        arguments:
            - "@madeyourday.rocksolid_slider.slideprovider.slider_model_adapter"
            - "@madeyourday.rocksolid_slider.slideprovider.slide_model_adapter"
            - "@madeyourday.rocksolid_slider.slideprovider.frontend_adapter"
        tags:
            - { name: madeyourday.rocksolid_slider.slideprovider }

    madeyourday.rocksolid_slider.slideprovider.events:
        class: MadeYourDay\RockSolidSlider\SlideProvider\EventsSlideProvider
        arguments:
            - "@madeyourday.rocksolid_slider.slideprovider.module_model_adapter"
        tags:
            - { name: madeyourday.rocksolid_slider.slideprovider }

    madeyourday.rocksolid_slider.slideprovider.news:
        class: MadeYourDay\RockSolidSlider\SlideProvider\NewsSlideProvider
        arguments:
            - "@madeyourday.rocksolid_slider.slideprovider.module_model_adapter"
        tags:
            - { name: madeyourday.rocksolid_slider.slideprovider }
